export const projectsPortfolio = [
  {
    id: 'rafinstal',
    title: 'Rafinstal',
    subtitle: 'Website',
    url: 'www.rafinstal.pl',
    p1: 'Rafinstal is a one-person company specializing in the installation of ventilation and heat recovery systems in office buildings, commercial properties, and single-family homes.',
    p2: "The website is based on the Smartwww theme for construction and service businesses. The extensive Offer subpages allow for a comprehensive presentation of our client's individual services. With the expanded gallery on the Projects subpage, they can showcase all their previous work. Numerous call-to-action sections and the Contact page enable website users to quickly establish cooperation with our client.",
    image: 'rafinstal.png',
    preview: 'rafinstal-preview.jpeg',
  },
  {
    id: 'rehmo',
    title: 'Rehmo',
    subtitle: 'Website',
    url: 'www.rehmo.pl',
    p1: 'Rehmo is a urogynecological rehabilitation clinic, operated by a certified rehabilitation specialist with extensive experience.',
    p2: 'The website is based on the Smartwww Personal theme. It includes all the necessary subpages to present the full range of services offered by the clinic and build the personal brand of its owner. The "About Us" subpage provides basic information about the clinic, a comprehensive presentation of the services offered, a contact form, and an overview of the stages of cooperation with patients. The design of the website aligns well with the nature of the clinic, featuring delicate, pastel colors and a user-friendly layout that instills trust and encourages potential patients to take advantage of the services.',
    image: 'rehmo.png',
    preview: 'rehmo-preview.jpeg',
  },
  {
    id: 'esovio',
    title: 'Esovio',
    subtitle: 'Website',
    url: 'www.esovio.pl',
    p1: 'Esovio is a medical store offering a range of medical products both in-store and online.',
    p2: 'The website features a blue-green color scheme, reminiscent of the medical industry. Aesthetically designed sections with icons allow visitors to familiarize themselves with all the product categories available in the store. The website has been designed to meet SEO requirements, hence the inclusion of numerous text sections seamlessly integrated into the layout of the page. Visitors can directly access the online store platform from the website.',
    image: 'esovio.png',
    preview: 'esovio-preview.jpg',
  },
  {
    id: 'otsusushi',
    title: 'Otsu Sushi',
    subtitle: 'Website',
    url: 'www.otsusushi.pl',
    p1: 'Otsu Sushi is a sushi restaurant located in Krakow, offering both dine-in and delivery services. The layout of the website is intended to evoke Asian culture and convey the high quality of the dishes served. This is achieved through the use of a minimalist and elegant color scheme and typography.',
    p2: 'The extensive structure of subpages allows users to explore the rich menu of the restaurant in detail, as well as the delivery areas. The website has been optimized for SEO, which is why we included a relatively large amount of text in an aesthetically pleasing manner without compromising readability. Additionally, the website features a blog that allows users to learn more about the rich Asian culture and an external module for handling deliveries.',
    image: 'otsusushi.png',
    preview: 'otsusushi-preview.jpeg',
  },
  {
    id: 'wloczykij',
    title: 'Włóczykij',
    subtitle: 'Website',
    url: 'www.wloczykij.edu.pl',
    p1: 'Włóczykij is a travel agency specializing in trips and camps for children and youth. They offer a wide range of excursions, summer camps, nature schools, and winter camps in Poland and abroad.',
    p2: 'The website design incorporates fresh colors and modern typography, reflecting the company\'s profile and catering primarily to young audiences. The website has a clear structure that allows for a comprehensive presentation of the excursion offerings categorized by different themes. With an intuitive and user-friendly CMS, the client can independently add or modify individual trips and provide information about their availability. The "Career" module enables the posting of current job offers. The website also supports multiple language versions.',
    image: 'wloczykij.png',
    preview: 'wloczykij-preview.jpg',
  },
  {
    id: 'parkcash',
    title: 'ParkCash',
    subtitle: 'Website',
    url: 'www.parkcash.io',
    p1: 'ParkCash is a startup offering innovative parking management technology based on the concept of sustainable development. The solution is designed for both office and commercial parking lots, as well as residential parking areas.',
    p2: "The ParkCash website is equipped with all the elements that allow users to quickly familiarize themselves with the proposed solution. An attractive top section with a video effectively grabs the audience's attention. The clear and user-friendly structure of the subpages allows users to explore all aspects of the service. The blog keeps users up to date with the company's news, as well as topics related to ecology and technology. The website also includes a detailed FAQ section and an extensive instruction manual featuring screenshots of the ParkCash application along with descriptions of its functionality. Additionally, we have prepared three landing pages where our client can encourage users to take specific actions.",
    image: 'parkcash.png',
    preview: 'parkcash-preview.jpg',
  },
  {
    id: 'villa-tabiki',
    title: 'Villa Tabiki',
    subtitle: 'Website',
    url: 'www.villatabiki.com',
    p1: 'Villa Tabiki is a residence located in the picturesque scenery near Coson Beach in the Dominican Republic. Guests can relax both in the villa itself and in the nearby apartment.',
    p2: "The villa's website is designed in an elegant style that emphasizes the exclusive nature of the property. Numerous photo galleries allow users to familiarize themselves with the appearance of the complex. In addition to a contact form, the website is equipped with a reservation module. The website also offers multiple language versions.",
    image: 'villa-tabiki.png',
    preview: 'villa-tabiki-preview.jpg',
  },
  {
    id: 'ostoja',
    title: 'Ostoja',
    subtitle: 'Website',
    url: 'www.ostojagarden.pl',
    p1: 'Ostoja Garden is a restaurant and hotel complex located near Kalwaria Zebrzydowska. Its offer is aimed at a wide range of guests, including couples, families with children, and business clients.',
    p2: 'The black and white layout with golden accents, along with a serif font, emphasizes the elegant character of the establishment. On the website, users can find the full restaurant menu and explore detailed information, including downloadable files, about accommodation options and event organization. The website is equipped with a room reservation module.',
    image: 'ostoja.png',
    preview: 'ostoja-preview.jpg',
  },
  {
    id: 'owe',
    title: 'Olkuskie Wyroby Emaliowane',
    subtitle: 'Website',
    url: 'olkuskiewyrobyemaliowane.pl',
    p1: 'Olkuskie Wyroby Emaliowane is a Polish company that continues the long-standing tradition of handcrafting enamelware and pots in Olkusz.',
    p2: "The website aims to showcase the wide range of enamel products offered by the company, hence the numerous galleries, often presented in the form of carousels. The contact form allows for placing individual orders. A dynamic counter highlights the rich tradition of the workshop, while the PDF files available on the website allow visitors to explore the brand's catalogs. The website also supports multiple language versions.",
    image: 'owe.png',
    preview: 'owe-preview.jpg',
  },
  {
    id: 'greensteam',
    title: 'GreenSteam',
    subtitle: 'Website',
    url: 'www.greensteam.pl',
    p1: 'GreenSteam is a company with years of experience in the field of steam cleaning and disinfection devices.',
    p2: "In this case, we opted for a clear and modern design that allows users to quickly navigate through the company's offerings as soon as they land on the website. The dominant green color refers to the logos color scheme and evokes associations with ecology, which is crucial in GreenSteam's operations. Numerous graphical modules and text sections enable the presentation of all services and products. The website facilitates navigation with an extensive system of internal links. For this client, it was crucial to enable users to send individual inquiries about their offerings, hence the inclusion of various contact features such as a call button, chatbot, and contact form.",
    image: 'greensteam.jpg',
    preview: 'greensteam-preview.jpg',
  },
  {
    id: 'wmn-agh',
    title: 'WMN AGH',
    subtitle: 'Website',
    url: 'www.wmn.agh.edu.pl',
    p1: 'The Faculty of Non-Ferrous Metals is a unit of the AGH University of Science and Technology in Krakow. It conducts research in the field of non-ferrous metals and carries out extensive scientific and educational activities.',
    p2: "The website aims to reflect the faculty's motto of preserving tradition while embracing a modern approach to education. The convenient side menu, present on each subpage, allows for smooth navigation through the extensive website structure. External modules, such as university email and e-learning, expand the website's content. Dynamic elements such as sliders, expandable tabs, and interactive maps enhance the attractiveness of the website, especially for young people who constitute a significant user group.",
    image: 'wmn-agh.png',
    preview: 'wmn-agh-preview.jpg',
  },
  {
    id: 'kusak',
    title: 'Kancelaria KK',
    subtitle: 'Website',
    url: 'www.kancelariakkp.pl',
    p1: 'Kancelaria Kusak Krzyszowski i Partnerzy is a professional law firm specializing in economic criminal law and bankruptcy proceedings.',
    p2: "The website of Kancelaria KK combines elegance with simplicity. It is a perfect website for a small firm. The featured tiles at the top of the web page allow users to quickly navigate to their desired topics. The counter on the website provides clear and transparent information about the effectiveness of the firm's actions.",
    image: 'kusak.jpg',
    preview: 'kusak-preview.jpg',
  },
  {
    id: 'mck',
    title: 'MCK Politechnika',
    subtitle: 'Website',
    url: 'www.mck.pk.edu.pl',
    p1: 'Międzynarodowe Centrum Kształcenia (International Education Center) is an interdisciplinary unit of the Krakow University of Technology.',
    p2: 'The website serves as a showcase for the International Education Center, providing essential information and news about the center. The website supports multiple language versions, allowing both Polish- and English-speaking students to quickly access the Student Zone and easily find various recruitment-related information. The user-friendly side navigation on subpages facilitates navigation throughout the website.',
    image: 'mck.jpg',
    preview: 'mck-preview.jpg',
  },
  {
    id: 'vineo',
    title: 'Vineo',
    subtitle: 'Website',
    url: 'www.vineo.pl',
    p1: 'Vineo is a website created out of passion for wine. It features publications with interesting facts, information about grape varieties, and the countries of their origin.',
    p2: 'Vineo is built on a blog system. It allows users to register, manage their profiles, and add posts. Additionally, statistics are kept for the most active authors. The blog has several categories accessible from the main menu. Vineo allows users to comment on and rate posts.',
    image: 'vineo.jpg',
    preview: 'vineo-preview.jpg',
  },
  {
    id: 'tacaonline',
    title: 'tacaonline.pl',
    subtitle: 'Website',
    url: 'www.tacaonline.pl',
    p1: 'tacaonline.pl is an online portal that enables electronic fundraising for parishes.',
    p2: 'The project was created to support parishes during the COVID-19 pandemic in Poland. tacaonline.pl allows any parish in the country to register and collect donations through integration with Przelewy24, a popular online payment platform. Each parish gains a dedicated page on the portal accessible through a separate link, as well as widgets that can be placed on their own website. The website utilizes Responsive Web Design (RWD) technology, and a dedicated API has been prepared to facilitate easy and dynamic generation of subpages for all parishes.',
    image: 'tacaonline.jpg',
    preview: 'tacaonline-preview.jpg',
  },
  {
    id: 'css',
    title: 'CCS',
    subtitle: 'Website',
    url: 'cablecarservices.com',
    p1: 'CCS is a company in the cable car industry, serving clients worldwide.',
    p2: "The CCS website incorporates numerous features aimed at showcasing the global nature of the company. Supporting multiple language versions is a fundamental function that adapts the website for international audiences. The world map displaying completed projects vividly demonstrates the company's broad scope of operations. A blog module has also been implemented on the website, allowing CCS to present itself as an expert in the field through the shared content.",
    image: 'ccs.jpg',
    preview: 'ccs-preview.jpg',
  },
];
